__version__='1.0.0'
__author__='Kenny Donahue'
__maintainer__='Kenny Donahue'
__url__='https://github.com/unbeforkinglievable/garden'
__description__='Package for interfacing with things in the garden'
